### ISSUE TITLE
Should form__field be a component on its own?

### ISSUE THREAD

**Issue by remco-freshheads** [freshheads/maatcss#9]
At this point there are two form input components: `form-choice` and `form-select`. `form__field` is a child from `form`. Looking at consistency and the fact that a form field can be used on it's own, I believe the `form__field` should be a component itself: `form-field`. 

In these components we could style the form validation like it's already been done, requiring the user to use `form__group` as a parent. Therefore some changes needs to be made, because in the current components we only check if there's a `has-error` class before the corresponding component. This should be `.form__group.has-error &`, imho.  

(We could disqus that `form__group` should be a component, but that will be another discussion 😄 .)

Let me know what you think of this topic!

**Comment by gijsvanzon** [comment]
I don't agree that form__field can be used on its own. If it would be a field on its own the class would be 'field'. The form prefix implies that it's part of the form tag, and always is part of the form tag. If we want to use the field as stand alone, I'm opting calling it field, field--toggle, etc. Instead of form-field.

**Comment by remco-freshheads** [comment]
Sure, that will do. But what about `form-choice` and `form-select`. Both of them are a component, but also both implying that they are part of the form tag.
